// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockItemReader is a mock of ItemReader interface.
type MockItemReader struct {
	ctrl     *gomock.Controller
	recorder *MockItemReaderMockRecorder
}

// MockItemReaderMockRecorder is the mock recorder for MockItemReader.
type MockItemReaderMockRecorder struct {
	mock *MockItemReader
}

// NewMockItemReader creates a new mock instance.
func NewMockItemReader(ctrl *gomock.Controller) *MockItemReader {
	mock := &MockItemReader{ctrl: ctrl}
	mock.recorder = &MockItemReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemReader) EXPECT() *MockItemReaderMockRecorder {
	return m.recorder
}

// GetAllItems mocks base method.
func (m *MockItemReader) GetAllItems() (*[]Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllItems")
	ret0, _ := ret[0].(*[]Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllItems indicates an expected call of GetAllItems.
func (mr *MockItemReaderMockRecorder) GetAllItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllItems", reflect.TypeOf((*MockItemReader)(nil).GetAllItems))
}

// GetItem mocks base method.
func (m *MockItemReader) GetItem(conds ...interface{}) (*Item, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItem", varargs...)
	ret0, _ := ret[0].(*Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockItemReaderMockRecorder) GetItem(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockItemReader)(nil).GetItem), conds...)
}

// GetItems mocks base method.
func (m *MockItemReader) GetItems(conds ...interface{}) (*[]Item, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItems", varargs...)
	ret0, _ := ret[0].(*[]Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockItemReaderMockRecorder) GetItems(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockItemReader)(nil).GetItems), conds...)
}

// MockItemWriter is a mock of ItemWriter interface.
type MockItemWriter struct {
	ctrl     *gomock.Controller
	recorder *MockItemWriterMockRecorder
}

// MockItemWriterMockRecorder is the mock recorder for MockItemWriter.
type MockItemWriterMockRecorder struct {
	mock *MockItemWriter
}

// NewMockItemWriter creates a new mock instance.
func NewMockItemWriter(ctrl *gomock.Controller) *MockItemWriter {
	mock := &MockItemWriter{ctrl: ctrl}
	mock.recorder = &MockItemWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemWriter) EXPECT() *MockItemWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateItem mocks base method.
func (m *MockItemWriter) CreateOrUpdateItem(item *Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateItem indicates an expected call of CreateOrUpdateItem.
func (mr *MockItemWriterMockRecorder) CreateOrUpdateItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateItem", reflect.TypeOf((*MockItemWriter)(nil).CreateOrUpdateItem), item)
}

// RemoveItem mocks base method.
func (m *MockItemWriter) RemoveItem(itemId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", itemId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockItemWriterMockRecorder) RemoveItem(itemId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockItemWriter)(nil).RemoveItem), itemId)
}

// RemoveTagFromItem mocks base method.
func (m *MockItemWriter) RemoveTagFromItem(itemId, tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromItem", itemId, tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromItem indicates an expected call of RemoveTagFromItem.
func (mr *MockItemWriterMockRecorder) RemoveTagFromItem(itemId, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromItem", reflect.TypeOf((*MockItemWriter)(nil).RemoveTagFromItem), itemId, tagId)
}

// UpdateItem mocks base method.
func (m *MockItemWriter) UpdateItem(item *Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockItemWriterMockRecorder) UpdateItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockItemWriter)(nil).UpdateItem), item)
}

// MockItemReaderWriter is a mock of ItemReaderWriter interface.
type MockItemReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockItemReaderWriterMockRecorder
}

// MockItemReaderWriterMockRecorder is the mock recorder for MockItemReaderWriter.
type MockItemReaderWriterMockRecorder struct {
	mock *MockItemReaderWriter
}

// NewMockItemReaderWriter creates a new mock instance.
func NewMockItemReaderWriter(ctrl *gomock.Controller) *MockItemReaderWriter {
	mock := &MockItemReaderWriter{ctrl: ctrl}
	mock.recorder = &MockItemReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemReaderWriter) EXPECT() *MockItemReaderWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateItem mocks base method.
func (m *MockItemReaderWriter) CreateOrUpdateItem(item *Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateItem indicates an expected call of CreateOrUpdateItem.
func (mr *MockItemReaderWriterMockRecorder) CreateOrUpdateItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateItem", reflect.TypeOf((*MockItemReaderWriter)(nil).CreateOrUpdateItem), item)
}

// GetAllItems mocks base method.
func (m *MockItemReaderWriter) GetAllItems() (*[]Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllItems")
	ret0, _ := ret[0].(*[]Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllItems indicates an expected call of GetAllItems.
func (mr *MockItemReaderWriterMockRecorder) GetAllItems() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllItems", reflect.TypeOf((*MockItemReaderWriter)(nil).GetAllItems))
}

// GetItem mocks base method.
func (m *MockItemReaderWriter) GetItem(conds ...interface{}) (*Item, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItem", varargs...)
	ret0, _ := ret[0].(*Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockItemReaderWriterMockRecorder) GetItem(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockItemReaderWriter)(nil).GetItem), conds...)
}

// GetItems mocks base method.
func (m *MockItemReaderWriter) GetItems(conds ...interface{}) (*[]Item, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetItems", varargs...)
	ret0, _ := ret[0].(*[]Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItems indicates an expected call of GetItems.
func (mr *MockItemReaderWriterMockRecorder) GetItems(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItems", reflect.TypeOf((*MockItemReaderWriter)(nil).GetItems), conds...)
}

// RemoveItem mocks base method.
func (m *MockItemReaderWriter) RemoveItem(itemId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveItem", itemId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveItem indicates an expected call of RemoveItem.
func (mr *MockItemReaderWriterMockRecorder) RemoveItem(itemId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveItem", reflect.TypeOf((*MockItemReaderWriter)(nil).RemoveItem), itemId)
}

// RemoveTagFromItem mocks base method.
func (m *MockItemReaderWriter) RemoveTagFromItem(itemId, tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromItem", itemId, tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromItem indicates an expected call of RemoveTagFromItem.
func (mr *MockItemReaderWriterMockRecorder) RemoveTagFromItem(itemId, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromItem", reflect.TypeOf((*MockItemReaderWriter)(nil).RemoveTagFromItem), itemId, tagId)
}

// UpdateItem mocks base method.
func (m *MockItemReaderWriter) UpdateItem(item *Item) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateItem", item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateItem indicates an expected call of UpdateItem.
func (mr *MockItemReaderWriterMockRecorder) UpdateItem(item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateItem", reflect.TypeOf((*MockItemReaderWriter)(nil).UpdateItem), item)
}

// MockTagReader is a mock of TagReader interface.
type MockTagReader struct {
	ctrl     *gomock.Controller
	recorder *MockTagReaderMockRecorder
}

// MockTagReaderMockRecorder is the mock recorder for MockTagReader.
type MockTagReaderMockRecorder struct {
	mock *MockTagReader
}

// NewMockTagReader creates a new mock instance.
func NewMockTagReader(ctrl *gomock.Controller) *MockTagReader {
	mock := &MockTagReader{ctrl: ctrl}
	mock.recorder = &MockTagReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagReader) EXPECT() *MockTagReaderMockRecorder {
	return m.recorder
}

// GetAllTags mocks base method.
func (m *MockTagReader) GetAllTags() (*[]Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags")
	ret0, _ := ret[0].(*[]Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockTagReaderMockRecorder) GetAllTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockTagReader)(nil).GetAllTags))
}

// GetTag mocks base method.
func (m *MockTagReader) GetTag(conds ...interface{}) (*Tag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTag", varargs...)
	ret0, _ := ret[0].(*Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockTagReaderMockRecorder) GetTag(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockTagReader)(nil).GetTag), conds...)
}

// GetTags mocks base method.
func (m *MockTagReader) GetTags(conds ...interface{}) (*[]Tag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTags", varargs...)
	ret0, _ := ret[0].(*[]Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagReaderMockRecorder) GetTags(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagReader)(nil).GetTags), conds...)
}

// MockTagWriter is a mock of TagWriter interface.
type MockTagWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTagWriterMockRecorder
}

// MockTagWriterMockRecorder is the mock recorder for MockTagWriter.
type MockTagWriterMockRecorder struct {
	mock *MockTagWriter
}

// NewMockTagWriter creates a new mock instance.
func NewMockTagWriter(ctrl *gomock.Controller) *MockTagWriter {
	mock := &MockTagWriter{ctrl: ctrl}
	mock.recorder = &MockTagWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagWriter) EXPECT() *MockTagWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateTag mocks base method.
func (m *MockTagWriter) CreateOrUpdateTag(tag *Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateTag indicates an expected call of CreateOrUpdateTag.
func (mr *MockTagWriterMockRecorder) CreateOrUpdateTag(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTag", reflect.TypeOf((*MockTagWriter)(nil).CreateOrUpdateTag), tag)
}

// UpdateTag mocks base method.
func (m *MockTagWriter) UpdateTag(tag *Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockTagWriterMockRecorder) UpdateTag(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockTagWriter)(nil).UpdateTag), tag)
}

// MockTagReaderWriter is a mock of TagReaderWriter interface.
type MockTagReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTagReaderWriterMockRecorder
}

// MockTagReaderWriterMockRecorder is the mock recorder for MockTagReaderWriter.
type MockTagReaderWriterMockRecorder struct {
	mock *MockTagReaderWriter
}

// NewMockTagReaderWriter creates a new mock instance.
func NewMockTagReaderWriter(ctrl *gomock.Controller) *MockTagReaderWriter {
	mock := &MockTagReaderWriter{ctrl: ctrl}
	mock.recorder = &MockTagReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagReaderWriter) EXPECT() *MockTagReaderWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateTag mocks base method.
func (m *MockTagReaderWriter) CreateOrUpdateTag(tag *Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateTag indicates an expected call of CreateOrUpdateTag.
func (mr *MockTagReaderWriterMockRecorder) CreateOrUpdateTag(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateTag", reflect.TypeOf((*MockTagReaderWriter)(nil).CreateOrUpdateTag), tag)
}

// GetAllTags mocks base method.
func (m *MockTagReaderWriter) GetAllTags() (*[]Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTags")
	ret0, _ := ret[0].(*[]Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTags indicates an expected call of GetAllTags.
func (mr *MockTagReaderWriterMockRecorder) GetAllTags() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTags", reflect.TypeOf((*MockTagReaderWriter)(nil).GetAllTags))
}

// GetTag mocks base method.
func (m *MockTagReaderWriter) GetTag(conds ...interface{}) (*Tag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTag", varargs...)
	ret0, _ := ret[0].(*Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockTagReaderWriterMockRecorder) GetTag(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockTagReaderWriter)(nil).GetTag), conds...)
}

// GetTags mocks base method.
func (m *MockTagReaderWriter) GetTags(conds ...interface{}) (*[]Tag, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTags", varargs...)
	ret0, _ := ret[0].(*[]Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTags indicates an expected call of GetTags.
func (mr *MockTagReaderWriterMockRecorder) GetTags(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTags", reflect.TypeOf((*MockTagReaderWriter)(nil).GetTags), conds...)
}

// UpdateTag mocks base method.
func (m *MockTagReaderWriter) UpdateTag(tag *Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockTagReaderWriterMockRecorder) UpdateTag(tag interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockTagReaderWriter)(nil).UpdateTag), tag)
}

// MockTagAnnotationReader is a mock of TagAnnotationReader interface.
type MockTagAnnotationReader struct {
	ctrl     *gomock.Controller
	recorder *MockTagAnnotationReaderMockRecorder
}

// MockTagAnnotationReaderMockRecorder is the mock recorder for MockTagAnnotationReader.
type MockTagAnnotationReaderMockRecorder struct {
	mock *MockTagAnnotationReader
}

// NewMockTagAnnotationReader creates a new mock instance.
func NewMockTagAnnotationReader(ctrl *gomock.Controller) *MockTagAnnotationReader {
	mock := &MockTagAnnotationReader{ctrl: ctrl}
	mock.recorder = &MockTagAnnotationReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagAnnotationReader) EXPECT() *MockTagAnnotationReaderMockRecorder {
	return m.recorder
}

// GetTagAnnotation mocks base method.
func (m *MockTagAnnotationReader) GetTagAnnotation(conds ...interface{}) (*TagAnnotation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTagAnnotation", varargs...)
	ret0, _ := ret[0].(*TagAnnotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagAnnotation indicates an expected call of GetTagAnnotation.
func (mr *MockTagAnnotationReaderMockRecorder) GetTagAnnotation(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagAnnotation", reflect.TypeOf((*MockTagAnnotationReader)(nil).GetTagAnnotation), conds...)
}

// GetTagAnnotations mocks base method.
func (m *MockTagAnnotationReader) GetTagAnnotations(tagId uint64) ([]TagAnnotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagAnnotations", tagId)
	ret0, _ := ret[0].([]TagAnnotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagAnnotations indicates an expected call of GetTagAnnotations.
func (mr *MockTagAnnotationReaderMockRecorder) GetTagAnnotations(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagAnnotations", reflect.TypeOf((*MockTagAnnotationReader)(nil).GetTagAnnotations), tagId)
}

// MockTagAnnotationWriter is a mock of TagAnnotationWriter interface.
type MockTagAnnotationWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTagAnnotationWriterMockRecorder
}

// MockTagAnnotationWriterMockRecorder is the mock recorder for MockTagAnnotationWriter.
type MockTagAnnotationWriterMockRecorder struct {
	mock *MockTagAnnotationWriter
}

// NewMockTagAnnotationWriter creates a new mock instance.
func NewMockTagAnnotationWriter(ctrl *gomock.Controller) *MockTagAnnotationWriter {
	mock := &MockTagAnnotationWriter{ctrl: ctrl}
	mock.recorder = &MockTagAnnotationWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagAnnotationWriter) EXPECT() *MockTagAnnotationWriterMockRecorder {
	return m.recorder
}

// CreateTagAnnotation mocks base method.
func (m *MockTagAnnotationWriter) CreateTagAnnotation(tagAnnotation *TagAnnotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagAnnotation", tagAnnotation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagAnnotation indicates an expected call of CreateTagAnnotation.
func (mr *MockTagAnnotationWriterMockRecorder) CreateTagAnnotation(tagAnnotation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagAnnotation", reflect.TypeOf((*MockTagAnnotationWriter)(nil).CreateTagAnnotation), tagAnnotation)
}

// RemoveTag mocks base method.
func (m *MockTagAnnotationWriter) RemoveTag(tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockTagAnnotationWriterMockRecorder) RemoveTag(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockTagAnnotationWriter)(nil).RemoveTag), tagId)
}

// RemoveTagAnnotationFromTag mocks base method.
func (m *MockTagAnnotationWriter) RemoveTagAnnotationFromTag(tagId, annotationId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagAnnotationFromTag", tagId, annotationId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagAnnotationFromTag indicates an expected call of RemoveTagAnnotationFromTag.
func (mr *MockTagAnnotationWriterMockRecorder) RemoveTagAnnotationFromTag(tagId, annotationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagAnnotationFromTag", reflect.TypeOf((*MockTagAnnotationWriter)(nil).RemoveTagAnnotationFromTag), tagId, annotationId)
}

// MockTagAnnotationReaderWriter is a mock of TagAnnotationReaderWriter interface.
type MockTagAnnotationReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockTagAnnotationReaderWriterMockRecorder
}

// MockTagAnnotationReaderWriterMockRecorder is the mock recorder for MockTagAnnotationReaderWriter.
type MockTagAnnotationReaderWriterMockRecorder struct {
	mock *MockTagAnnotationReaderWriter
}

// NewMockTagAnnotationReaderWriter creates a new mock instance.
func NewMockTagAnnotationReaderWriter(ctrl *gomock.Controller) *MockTagAnnotationReaderWriter {
	mock := &MockTagAnnotationReaderWriter{ctrl: ctrl}
	mock.recorder = &MockTagAnnotationReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagAnnotationReaderWriter) EXPECT() *MockTagAnnotationReaderWriterMockRecorder {
	return m.recorder
}

// CreateTagAnnotation mocks base method.
func (m *MockTagAnnotationReaderWriter) CreateTagAnnotation(tagAnnotation *TagAnnotation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTagAnnotation", tagAnnotation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTagAnnotation indicates an expected call of CreateTagAnnotation.
func (mr *MockTagAnnotationReaderWriterMockRecorder) CreateTagAnnotation(tagAnnotation interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTagAnnotation", reflect.TypeOf((*MockTagAnnotationReaderWriter)(nil).CreateTagAnnotation), tagAnnotation)
}

// GetTagAnnotation mocks base method.
func (m *MockTagAnnotationReaderWriter) GetTagAnnotation(conds ...interface{}) (*TagAnnotation, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTagAnnotation", varargs...)
	ret0, _ := ret[0].(*TagAnnotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagAnnotation indicates an expected call of GetTagAnnotation.
func (mr *MockTagAnnotationReaderWriterMockRecorder) GetTagAnnotation(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagAnnotation", reflect.TypeOf((*MockTagAnnotationReaderWriter)(nil).GetTagAnnotation), conds...)
}

// GetTagAnnotations mocks base method.
func (m *MockTagAnnotationReaderWriter) GetTagAnnotations(tagId uint64) ([]TagAnnotation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTagAnnotations", tagId)
	ret0, _ := ret[0].([]TagAnnotation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTagAnnotations indicates an expected call of GetTagAnnotations.
func (mr *MockTagAnnotationReaderWriterMockRecorder) GetTagAnnotations(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTagAnnotations", reflect.TypeOf((*MockTagAnnotationReaderWriter)(nil).GetTagAnnotations), tagId)
}

// RemoveTag mocks base method.
func (m *MockTagAnnotationReaderWriter) RemoveTag(tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTag", tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTag indicates an expected call of RemoveTag.
func (mr *MockTagAnnotationReaderWriterMockRecorder) RemoveTag(tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTag", reflect.TypeOf((*MockTagAnnotationReaderWriter)(nil).RemoveTag), tagId)
}

// RemoveTagAnnotationFromTag mocks base method.
func (m *MockTagAnnotationReaderWriter) RemoveTagAnnotationFromTag(tagId, annotationId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagAnnotationFromTag", tagId, annotationId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagAnnotationFromTag indicates an expected call of RemoveTagAnnotationFromTag.
func (mr *MockTagAnnotationReaderWriterMockRecorder) RemoveTagAnnotationFromTag(tagId, annotationId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagAnnotationFromTag", reflect.TypeOf((*MockTagAnnotationReaderWriter)(nil).RemoveTagAnnotationFromTag), tagId, annotationId)
}

// MockDirectoryReader is a mock of DirectoryReader interface.
type MockDirectoryReader struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryReaderMockRecorder
}

// MockDirectoryReaderMockRecorder is the mock recorder for MockDirectoryReader.
type MockDirectoryReaderMockRecorder struct {
	mock *MockDirectoryReader
}

// NewMockDirectoryReader creates a new mock instance.
func NewMockDirectoryReader(ctrl *gomock.Controller) *MockDirectoryReader {
	mock := &MockDirectoryReader{ctrl: ctrl}
	mock.recorder = &MockDirectoryReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryReader) EXPECT() *MockDirectoryReaderMockRecorder {
	return m.recorder
}

// GetAllDirectories mocks base method.
func (m *MockDirectoryReader) GetAllDirectories() (*[]Directory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDirectories")
	ret0, _ := ret[0].(*[]Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDirectories indicates an expected call of GetAllDirectories.
func (mr *MockDirectoryReaderMockRecorder) GetAllDirectories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDirectories", reflect.TypeOf((*MockDirectoryReader)(nil).GetAllDirectories))
}

// GetDirectories mocks base method.
func (m *MockDirectoryReader) GetDirectories(conds ...interface{}) (*[]Directory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDirectories", varargs...)
	ret0, _ := ret[0].(*[]Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectories indicates an expected call of GetDirectories.
func (mr *MockDirectoryReaderMockRecorder) GetDirectories(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectories", reflect.TypeOf((*MockDirectoryReader)(nil).GetDirectories), conds...)
}

// GetDirectory mocks base method.
func (m *MockDirectoryReader) GetDirectory(conds ...interface{}) (*Directory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDirectory", varargs...)
	ret0, _ := ret[0].(*Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectory indicates an expected call of GetDirectory.
func (mr *MockDirectoryReaderMockRecorder) GetDirectory(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectory", reflect.TypeOf((*MockDirectoryReader)(nil).GetDirectory), conds...)
}

// MockDirectoryWriter is a mock of DirectoryWriter interface.
type MockDirectoryWriter struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryWriterMockRecorder
}

// MockDirectoryWriterMockRecorder is the mock recorder for MockDirectoryWriter.
type MockDirectoryWriterMockRecorder struct {
	mock *MockDirectoryWriter
}

// NewMockDirectoryWriter creates a new mock instance.
func NewMockDirectoryWriter(ctrl *gomock.Controller) *MockDirectoryWriter {
	mock := &MockDirectoryWriter{ctrl: ctrl}
	mock.recorder = &MockDirectoryWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryWriter) EXPECT() *MockDirectoryWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateDirectory mocks base method.
func (m *MockDirectoryWriter) CreateOrUpdateDirectory(directory *Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateDirectory", directory)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateDirectory indicates an expected call of CreateOrUpdateDirectory.
func (mr *MockDirectoryWriterMockRecorder) CreateOrUpdateDirectory(directory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateDirectory", reflect.TypeOf((*MockDirectoryWriter)(nil).CreateOrUpdateDirectory), directory)
}

// RemoveDirectory mocks base method.
func (m *MockDirectoryWriter) RemoveDirectory(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDirectory", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDirectory indicates an expected call of RemoveDirectory.
func (mr *MockDirectoryWriterMockRecorder) RemoveDirectory(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDirectory", reflect.TypeOf((*MockDirectoryWriter)(nil).RemoveDirectory), path)
}

// RemoveTagFromDirectory mocks base method.
func (m *MockDirectoryWriter) RemoveTagFromDirectory(direcotryPath string, tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromDirectory", direcotryPath, tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromDirectory indicates an expected call of RemoveTagFromDirectory.
func (mr *MockDirectoryWriterMockRecorder) RemoveTagFromDirectory(direcotryPath, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromDirectory", reflect.TypeOf((*MockDirectoryWriter)(nil).RemoveTagFromDirectory), direcotryPath, tagId)
}

// MockDirectoryReaderWriter is a mock of DirectoryReaderWriter interface.
type MockDirectoryReaderWriter struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryReaderWriterMockRecorder
}

// MockDirectoryReaderWriterMockRecorder is the mock recorder for MockDirectoryReaderWriter.
type MockDirectoryReaderWriterMockRecorder struct {
	mock *MockDirectoryReaderWriter
}

// NewMockDirectoryReaderWriter creates a new mock instance.
func NewMockDirectoryReaderWriter(ctrl *gomock.Controller) *MockDirectoryReaderWriter {
	mock := &MockDirectoryReaderWriter{ctrl: ctrl}
	mock.recorder = &MockDirectoryReaderWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryReaderWriter) EXPECT() *MockDirectoryReaderWriterMockRecorder {
	return m.recorder
}

// CreateOrUpdateDirectory mocks base method.
func (m *MockDirectoryReaderWriter) CreateOrUpdateDirectory(directory *Directory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrUpdateDirectory", directory)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrUpdateDirectory indicates an expected call of CreateOrUpdateDirectory.
func (mr *MockDirectoryReaderWriterMockRecorder) CreateOrUpdateDirectory(directory interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrUpdateDirectory", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).CreateOrUpdateDirectory), directory)
}

// GetAllDirectories mocks base method.
func (m *MockDirectoryReaderWriter) GetAllDirectories() (*[]Directory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllDirectories")
	ret0, _ := ret[0].(*[]Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllDirectories indicates an expected call of GetAllDirectories.
func (mr *MockDirectoryReaderWriterMockRecorder) GetAllDirectories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllDirectories", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).GetAllDirectories))
}

// GetDirectories mocks base method.
func (m *MockDirectoryReaderWriter) GetDirectories(conds ...interface{}) (*[]Directory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDirectories", varargs...)
	ret0, _ := ret[0].(*[]Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectories indicates an expected call of GetDirectories.
func (mr *MockDirectoryReaderWriterMockRecorder) GetDirectories(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectories", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).GetDirectories), conds...)
}

// GetDirectory mocks base method.
func (m *MockDirectoryReaderWriter) GetDirectory(conds ...interface{}) (*Directory, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range conds {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDirectory", varargs...)
	ret0, _ := ret[0].(*Directory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirectory indicates an expected call of GetDirectory.
func (mr *MockDirectoryReaderWriterMockRecorder) GetDirectory(conds ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirectory", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).GetDirectory), conds...)
}

// RemoveDirectory mocks base method.
func (m *MockDirectoryReaderWriter) RemoveDirectory(path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDirectory", path)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDirectory indicates an expected call of RemoveDirectory.
func (mr *MockDirectoryReaderWriterMockRecorder) RemoveDirectory(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDirectory", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).RemoveDirectory), path)
}

// RemoveTagFromDirectory mocks base method.
func (m *MockDirectoryReaderWriter) RemoveTagFromDirectory(direcotryPath string, tagId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveTagFromDirectory", direcotryPath, tagId)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveTagFromDirectory indicates an expected call of RemoveTagFromDirectory.
func (mr *MockDirectoryReaderWriterMockRecorder) RemoveTagFromDirectory(direcotryPath, tagId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveTagFromDirectory", reflect.TypeOf((*MockDirectoryReaderWriter)(nil).RemoveTagFromDirectory), direcotryPath, tagId)
}

// MockStorageUploader is a mock of StorageUploader interface.
type MockStorageUploader struct {
	ctrl     *gomock.Controller
	recorder *MockStorageUploaderMockRecorder
}

// MockStorageUploaderMockRecorder is the mock recorder for MockStorageUploader.
type MockStorageUploaderMockRecorder struct {
	mock *MockStorageUploader
}

// NewMockStorageUploader creates a new mock instance.
func NewMockStorageUploader(ctrl *gomock.Controller) *MockStorageUploader {
	mock := &MockStorageUploader{ctrl: ctrl}
	mock.recorder = &MockStorageUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageUploader) EXPECT() *MockStorageUploaderMockRecorder {
	return m.recorder
}

// GetFileForWriting mocks base method.
func (m *MockStorageUploader) GetFileForWriting(name string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileForWriting", name)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileForWriting indicates an expected call of GetFileForWriting.
func (mr *MockStorageUploaderMockRecorder) GetFileForWriting(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileForWriting", reflect.TypeOf((*MockStorageUploader)(nil).GetFileForWriting), name)
}

// GetStorageUrl mocks base method.
func (m *MockStorageUploader) GetStorageUrl(name string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStorageUrl", name)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetStorageUrl indicates an expected call of GetStorageUrl.
func (mr *MockStorageUploaderMockRecorder) GetStorageUrl(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStorageUrl", reflect.TypeOf((*MockStorageUploader)(nil).GetStorageUrl), name)
}

// GetTempFile mocks base method.
func (m *MockStorageUploader) GetTempFile() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTempFile")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetTempFile indicates an expected call of GetTempFile.
func (mr *MockStorageUploaderMockRecorder) GetTempFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTempFile", reflect.TypeOf((*MockStorageUploader)(nil).GetTempFile))
}

// MockDirectoryItemsGetter is a mock of DirectoryItemsGetter interface.
type MockDirectoryItemsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockDirectoryItemsGetterMockRecorder
}

// MockDirectoryItemsGetterMockRecorder is the mock recorder for MockDirectoryItemsGetter.
type MockDirectoryItemsGetterMockRecorder struct {
	mock *MockDirectoryItemsGetter
}

// NewMockDirectoryItemsGetter creates a new mock instance.
func NewMockDirectoryItemsGetter(ctrl *gomock.Controller) *MockDirectoryItemsGetter {
	mock := &MockDirectoryItemsGetter{ctrl: ctrl}
	mock.recorder = &MockDirectoryItemsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirectoryItemsGetter) EXPECT() *MockDirectoryItemsGetterMockRecorder {
	return m.recorder
}

// GetBelongingItems mocks base method.
func (m *MockDirectoryItemsGetter) GetBelongingItems(path string) (*[]Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBelongingItems", path)
	ret0, _ := ret[0].(*[]Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBelongingItems indicates an expected call of GetBelongingItems.
func (mr *MockDirectoryItemsGetterMockRecorder) GetBelongingItems(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBelongingItems", reflect.TypeOf((*MockDirectoryItemsGetter)(nil).GetBelongingItems), path)
}
